require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe OffersController, type: :controller do

  before(:each) do
    @admin = FactoryBot.create(:admin)
    request.env["devise.mapping"] = Devise.mappings[:admin]
    sign_in @admin
  end

  after(:each) do
    sign_out @admin
  end

  # This should return the minimal set of attributes required to create a valid
  # Offer. As you add validations to Offer, be sure to
  # adjust the attributes here as well.
  def valid_attributes
    {
      offer: 
        {
          advertiser_name: "Rohan-Terry",
          url: "http://kihn.name/sydni",
          description: "Automated eco-centric migration",
          starts_at: Time.zone.now - 1.day,
          ends_at: Time.zone.now + 1.year,
          premium: "false"
        }
    }
  end

  def invalid_attributes
    {
      offer: 
        {
          advertiser_name: "McCullough Inc"
        }
    }
  end

  def valid_update_attributes
    {
      offer: {
        description: "We do awesome stuff"
      }
    }
  end

  def invalid_update_attributes
    {
      offer: {
        url: "this-is-not-a-url"
      }
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OffersController. Be sure to keep this updated too.

  describe "GET #index" do
    it "returns a success response" do
      offer = Offer.create! valid_attributes[:offer]
      get :index, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      offer = Offer.create! valid_attributes[:offer]
      get :edit, params: {id: offer.id}
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Offer" do
        expect {
          post :create, params: valid_attributes
        }.to change(Offer, :count).by(1)
      end

      it "redirects to the offers list" do
        post :create, params: valid_attributes
        expect(response).to redirect_to(offers_url)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: invalid_attributes
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do

      it "updates the requested offer" do
        offer = Offer.create! valid_attributes[:offer]
        put :update, params: valid_update_attributes.merge!(id: offer.id)
        offer.reload
        expect(offer.description).to eq(valid_update_attributes[:offer][:description])
      end

      it "redirects to the offers list" do
        offer = Offer.create! valid_attributes[:offer]
        put :update, params: valid_update_attributes.merge!(id: offer.id)
        expect(response).to redirect_to(offers_url)
      end
    end

    context "with invalid params" do

      it "doesn't update the requested offer" do
        offer = Offer.create! valid_attributes[:offer]
        put :update, params: invalid_update_attributes.merge!(id: offer.id)
        offer.reload
        expect(offer.description).to eq(valid_attributes[:offer][:description])
      end

      it "returns a success response (i.e. to display the 'edit' template)" do
        offer = Offer.create! valid_attributes[:offer]
        put :update, params: invalid_update_attributes.merge!(id: offer.id)
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested offer" do
      offer = Offer.create! valid_attributes[:offer]
      expect {
        delete :destroy, params: {id: offer.to_param}
      }.to change(Offer, :count).by(-1)
    end

    it "redirects to the offers list" do
      offer = Offer.create! valid_attributes[:offer]
      delete :destroy, params: {id: offer.to_param}
      expect(response).to redirect_to(offers_url)
    end
  end

end
